layout: sidebar
style: dark #can switch to light or dark depending on desired style

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  sort_by options:
    - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
      - Curriculum-Vitae
      - GeneralHaskell
    # - repo-name

#social_media.yml and social_media_share_url.html
social_media:
  linkedin: malcolm-st-john-3343a958
  twitter: TheArcticWalrus
  instagram: arcticwalrus
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username

topics:
  - name: Haskell
    web_url: https://github.com/topics/haskell
    image_url: https://www.haskell.org/img/haskell-logo.svg

  - name: Linux Kernel
    web_url : https://github.com/topics/linux
    image_url : https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/linux/linux.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1024px-Python-logo-notext.svg.png

theme: jekyll-theme-slate